---
pagetitle: "Publications"
output:
  html_document: 
    toc: true
    toc_float: true
---
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
<!-- Specifics for including altmetric on the homepage -->
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>

<link rel="stylesheet" href="styles.css" type="text/css">

I have a profile on [Google Scholar](https://scholar.google.com/citations?hl=en&user=UI4wCAEAAAAJ){target="_blank"}.

## In-progress articles
<!----> 7. **Huguenin, M. F.**, Ryan, S., Ummenhofer, C. C. & England, M. H. (2024). Linking the recent decrease in Weddell Sea dense shelf water formation to shifts in the Interdecadal Pacific Oscillation. *In preparation*.

<!----> 6. England, M. H., Li, Z., **Huguenin, M. F.**, Kiss, A. E., Sen Gupta, A., Holmes, R. M. & Rahmstorf, S. (2024). Drivers of the unprecedented North Atlantic marine heat wave in 2023. *In review at Nature*.

## Peer-reviewed articles
<!----> 5. **Huguenin, M. F.**, Holmes, R. M., Spence, P. & England, M. H. (2024). [Subsurface warming of the West Antarctic continental shelf linked to El Niño-Southern Oscillation](https://doi.org/10.1029/2023GL104518). *Geophysical Research Letters*, 51, e2023GL104518.

<!-- <div class='altmetric-embed' data-badge-popover="left" data-badge-type='donut' data-hide-no-mentions="true" data-doi="10.1029/2019GL086132" style="float:right;"></div> -->

<!----> 4. **Huguenin, M. F.**, Holmes, R. M., & England, M. H. (2022). [Drivers and distribution of global ocean heat uptake over the last half century](https://doi.org/10.1038/s41467-022-32540-5). *Nature Communications*. 13, 4921.

<!----> 3. **Huguenin, M. F.**, Holmes, R. M., & England, M. H. (2020). [Key Role of Diabatic Processes in Regulating Warm Water Volume Variability Over ENSO Events](https://doi.org/10.1175/JCLI-D-20-0198.1). *Journal of Climate*. 33, 9945–9964.

<!----> 2. **Huguenin, M. F.**, Fischer, E. M., Kotlarski, S., Scherrer, S. C., Schwierz, C., & Knutti, R. (2020). [Lack of Change in the Projected Frequency and Persistence of Atmospheric Circulation Types Over Central Europe](https://doi.org/10.1029/2019GL086132). *Geophysical Research Letters*, 47.

<!----> 1. Santoso, A., Hendon, H., Watkins, A., Power, S., Dommenget, D., England, M. H., Frankcombe, L., Holbrook, N. J., Holmes, R. M., Hope, P., Lim, E., Luo, J., McGregor, S., Neske, S., Nguyen, H., Pepler, A., Rashid, H., Gupta, A. S., Taschetto, A. S., Wang, G., Abellán, E., Sullivan, A., **Huguenin, M. F.**, Gamble, F. & Delage, F. (2019). [Dynamics and Predictability of El Niño-Southern Oscillation: An Australian Perspective on Progress and Challenges](https://doi.org/10.1175/BAMS-D-18-0057.1). *Bulletin of the American Meteorological Society*, 100, 403-420.

## Data sets and analysis code
<!----> 6. **Huguenin, M. F.**, Holmes, R. H., Spence, P. & England, M. H. (2024). ENSO-Antarctica_data (Version 20240118) [Data set]. Zenodo. [https://doi.org/10.5281/zenodo.10526062](https://doi.org/10.5281/zenodo.10526062).

<!----> 5. **Huguenin, M. F.**, Holmes, R. H., Spence, P. & England, M. H. (2024). ENSO-Antarctica_scripts (20240126_v2) [Analysis code]. Zenodo.
[https://doi.org/10.5281/zenodo.10570459](https://doi.org/10.5281/zenodo.10570459).

<!----> 4. **Huguenin, M. F.**, Holmes, R. H. & England, M. H. (2023). ACCESS-OM2 1° resolution global repeat decade full forcing interannual simulation data for 1972-2018 (1.0) [Data set]. Zenodo. [https://doi.org/10.5281/zenodo.8343648](https://doi.org/10.5281/zenodo.8343648).

<!----> 3. **Huguenin, M. F.**, Holmes, R. H. & England, M. H. (2023). ACCESS-OM2 1° resolution global repeat decade forcing control simulation data for 1972-2018 (1.0) [Data set]. Zenodo. [https://doi.org/10.5281/zenodo.8339578](https://doi.org/10.5281/zenodo.8339578).

<!----> 2. **Huguenin, M. F.**, Holmes, R. H. & England, M. H. (2022). Data and analysis scripts for Huguenin et al. (2022), Nature Communications (20220721_v2) [Analysis code]. Zenodo. [https://doi.org/10.5281/zenodo.6873094](https://doi.org/10.5281/zenodo.6873094).

<!----> 1. **Huguenin, M. F.**, Fischer, E. M., Kotlarski, S., Scherrer, S. C., Schwierz, C., & Knutti, R. (2020) mauricehuguenin/europe_circulation_types: Analysis Scripts and Data (20240628_v2) [Analysis scripts and data]. Zenodo. [https://doi.org/10.5281/zenodo.12578019](https://doi.org/10.5281/zenodo.12578019).

## Theses
- **Huguenin, M. F.** (2023). [Processes and Dynamics of Global to Regional Ocean Heat Uptake and Variability](https://doi.org/10.26190/unsworks/25224). Doctoral Thesis, Climate Change Research Centre, UNSW Sydney, Sydney, Australia. [2-page summary](files/Huguenin_Maurice_Thesis_Summary_20241219.pdf).


- **Huguenin, M. F.**. (2018). [Mechanisms Driving Ocean Heat Uptake and Warm Water Volume Variability During Idealized ENSO Events](files/msc_thesis_maurice_huguenin_2018.pdf). Master Thesis, Institute for Atmospheric and Climate Science, ETH Zurich, Zurich, Switzerland.

- **Huguenin, M. F.**. (2016). [Ocean Heat Storage And Implications On Sea Level Rise Using CCSM4 Model Output For 1993-2016](files/bsc_thesis_maurice_huguenin_2016.pdf). Bachelor Thesis, Institute for Atmospheric and Climate Science, ETH Zurich, Zurich, Switzerland.


## Media
- The Conversation: [Heat from El Niño can warm oceans off West Antarctica – and melt floating ice shelves from below](https://theconversation.com/heat-from-el-nino-can-warm-oceans-off-west-antarctica-and-melt-floating-ice-shelves-from-below-226233)
- The Academic Minute: [Southern Ocean Takes on the Heat of Climate Change](https://academicminute.org/2022/12/maurice-huguenin-university-of-new-south-wales-southern-ocean-takes-on-the-heat-of-climate-change/)
- UNSW Newsroom: [Southern Ocean takes on the heat of climate change](https://newsroom.unsw.edu.au/news/science-tech/southern-ocean-takes-heat-climate-change)
- The Conversation: [The Southern Ocean absorbs more heat than any other ocean on Earth, and the impacts will be felt for generations](https://theconversation.com/the-southern-ocean-absorbs-more-heat-than-any-other-ocean-on-earth-and-the-impacts-will-be-felt-for-generations-189561)
- CLEX Newsletter: [Towards an increased understanding of the East Australian Current – My voyage abord RV Investigator](https://climateextremes.org.au/towards-an-increased-understanding-of-the-east-australian-current-my-voyage-abord-rv-investigator/)
- Dorfzeitung Binde-Strich: [Ein Pfungemer auf hoher See](media/BindeStrich_08_21_Seite21.pdf) 
- UNSW Newsroom: [Four weeks voyage yields secrets to changing oceans](https://newsroom.unsw.edu.au/news/science-tech/four-week-voyage-yields-secrets-changing-oceans)
- CLEX research brief: [Vertical Mixing and Air-Sea Heat Fluxes Play a Key Role in Driving ENSO-related Ocean Heat Content Changes](media/CLEX_ResearchBrief_ENSO_WWV_2020.pdf)
- CLEX research brief: [Current climate models do not project a more persistent Central European weather](https://climateextremes.org.au/research-brief-current-climate-models-do-not-project-a-more-persistent-central-european-circulation/)

<!-- A full list of publications is available at the above Google scholar link. -->


