---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Publications

<!-- Insert Altmetric link as on Martin Jucker's homepage -->

**Huguenin, M. F.**, Fischer, E. M., Kotlarski, S., Scherrer, S. C., Schwierz, C., & Knutti, R. (2020). Lack of Change in the Projected Frequency and Persistence of Atmospheric Circulation Types Over Central Europe. *Geophysical Research Letters*, **47**. [doi.org/10.1029/2019GL086132](https://doi.org/10.1029/2019GL086132)

Santoso, A., Hendon, H., Watkins, A., Power, S., Dommenget, D., England, M. H., Frankcombe, L., Holbrook, N. J., Holmes, R. M., Hope, P., Lim, E., Luo, J., McGregor, S., Neske, S., Nguyen, H., Pepler, A., Rashid, H., Gupta, A. S., Taschetto, A. S., Wang, G., Abellán, E., Sullivan, A., **Huguenin, M. F.**, Gamble, F. & Delage, F. (2019). Dynamics and Predictability of El Niño-Southern Oscillation: An Australian Perspective on Progress and Challenges. *Bulletin of the American Meteorological Society*, **100**, 403-420. [doi.org/10.1175/BAMS-D-18-0057.1](https://doi.org/10.1175/BAMS-D-18-0057.1)

## Theses

**Huguenin, M. F.**, 2018. **Mechanisms Driving Ocean Heat Uptake and Warm Water Volume Variability During Idealized ENSO Events.** Master Thesis, Institute for Atmospheric and Climate Science, ETH Zurich, Zurich, Switzerland [pdf](files/msc_thesis_maurice_huguenin_2018.pdf).

**Huguenin, M. F.**, 2016. **Ocean Heat Storage And Implications On Sea Level Rise Using CCSM4 Model Output For 1993-2016.** Bachelor Thesis, Institute for Atmospheric and Climate Science, ETH Zurich, Zurich, Switzerland [pdf](files/bsc_thesis_maurice_huguenin_2016.pdf).


## [Google scholar](https://scholar.google.com/citations?hl=en&user=UI4wCAEAAAAJ)

<!-- A full list of publications is available at the above Google scholar link. -->


