---
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

## Oral Presentations

2019, November 02-03. Diabatic Contributions to Warm Water Volume Variability During ENSO Events, Workshop on Ocean Warming and Sea Level Rise, UNSW Sydney, Australia

2019, June 11-14. Diabatic Contributions to Warm Water Volume Variability During ENSO Events, Australian Meteorological Society Annual Meeting, Darwin, Northern Territory, Australia [pdf](presentations/msc_thesis_presentation_maurice_huguenin_2019.pdf)

2019, April 17. Changes in the Frequency and Persistence of Central European Circulation Types, MeteoSwiss & ETH Seminars, Zurich, Switzerland [pdf](presentations/meteoswiss_eth_presentation_maurice_huguenin_2019.pdf)

## Poster Presentations

2020, February 16-21. Diabatic Contribution to Ocean Heat Variability during ENSO Events, Ocean Sciences Meeting, San Diego, California, United States of America [pdf](presentations/poster_ocean_sciences_conference_maurice_huguenin_2020.pdf)

2019, November 19-22. Discharge and Recharge of Ocean Heat during ENSO Events, CLEX Annual Workshop, Hobart, Tasmania, Australia [pdf](presentations/poster_clex_workshop_maurice_huguenin_2019.pdf), [pptx](presentations/poster_clex_workshop_maurice_huguenin_2019.pptx)

2019, June 11-14. Diabatic Contributions to Warm Water Volume Variability During ENSO Events, Australian Meteorological Society Annual Meeting, Darwin, Northern Territory, Australia [pdf](presentations/poster_amos_conference_maurice_huguenin_2019.pdf)

2019, April 09-12. Changes in the Frequency and Persistence of Central European Circulation Types, European Geophysical Union Annual Meeting, Vienna, Austria [pdf](presentations/poster_egu_conference_maurice_huguenin_2019.pdf), [pptx](presentations/poster_egu_conference_maurice_huguenin_2019.pptx)

2016, June 13. Ocean Heat Uptake and Implications on Sea Level Rise, Bachelor Seminar, ETH Zurich, Switzerland [pdf](presentations/poster_bsc_seminar_maurice_huguenin_2016.pdf)
